### ISSUE TITLE
Please add a homepage

### ISSUE THREAD

**Issue by pcav** [FloodRiskGroup/floodrisk#1]
This repo would do.
Thanks.

**Comment by FloodRiskGroup** [comment]
The home page will add it as soon as possible.
We are working at the FloodRisk website

**Comment by pcav** [comment]
I would suggest you to add a link to this repo for now, changing to a proper HP when ready.
This will speed up publication.
Thanks.

**Comment by FloodRiskGroup** [comment]
Ok we have added a temporary home page

**Comment by pcav** [comment]
OK, let me know when ready.
