### ISSUE TITLE
Error loading plugin into QGIS 2.14.1 (64-bit)

### ISSUE THREAD

**Issue by airving61** [FloodRiskGroup/floodrisk#3]
I received the following error message when installing the FloodRisk plugin into QGIS 2.14.1 (64-bit) running on Windows 7 Pro. Please advise what's the preferred solution? Should I try to install Pylab from https://pypi.python.org/pypi/pylab or somewhere else? Thanks in advance.

![2016-04-27_10h25_28](https://cloud.githubusercontent.com/assets/17354350/14851023/e93c6b7e-0c74-11e6-92d9-957b9710bff3.png)

**Comment by FloodRiskGroup** [comment]
The pylab module is part of the matplotlib installation, which by default is installed with QGIS.
If the module is not loaded there may be a QGIS installation problem: tries using the most stable version of QGIS (LTR Version 2.8.8)

**Comment by FloodRiskGroup** [comment]
The pylab module is part of the matplotlib installation, which by default is installed with QGIS.
If the module is not loaded there may be a QGIS installation problem: tries using the most stable version of QGIS (LTR Version 2.8.8)

**Comment by FloodRiskGroup** [comment]
The pylab module is part of the matplotlib installation, which by default is installed with QGIS.
If the module is not loaded there may be a QGIS installation problem: please try using the most stable version of QGIS (LTR Version 2.8.8)

**Comment by raffalba** [comment]
The pylab module is included in the QGIS 2.14.1 (64bit) stand-alone or advanced release. Moreover, I have installed these releases of QGIS on Windows 7 Professional finalizing the installation of FloodRisk plug-in without any issues. Therefore, I suggest to check the QGIS installtion on your pc. 
Finally, The FloodRisk plugin is developed and tested on the long term release QGIS 2.8, therefore, we can guarantee the compatibility with this QGIS releases. I hope our comments were helpful for you. Thanks for posting your comments helping us to test and improve this collaborative tool.

**Comment by airving61** [comment]
Thanks for the reply. The installation of 2.14.1 was a fresh one and no errors have been reported for other plug-ins. Nevertheless, I'll try it with the LTR version 2.8.3 and see what happens.
