### ISSUE TITLE
Error: no OccuType field 

### ISSUE THREAD

**Issue by bernoulli1** [FloodRiskGroup/floodrisk#6]
I´m still having the problem, I´ve installed the files in this page however at the time that I try to load the shp files "Property Polygon" and "Infrastructures Lines". 
Does anybody solve the problem?[
![Screenshot_1](https://user-images.githubusercontent.com/69941603/90699332-97c4c800-e248-11ea-81ff-61a1ee188ed2.jpg)
](url)

**Comment by FloodRiskGroup** [comment]
The problem is generated by an unexpected behavior of a query operation of the ogr library in the LoadGeodatiFloodRisk.py module. The problem is solved by updating the module. It is now possible download the updated plugin.
